CC=gcc
CFLAGS=-Wall -Wextra
CLIBS=-lm

q1: 1-monte.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q2: 2-queue.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q3: 3-markov.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q4: 4-lcm.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q5: 5-mcm.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q6: 6-midSquare.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q7: 7-ks.c
	${CC} $^ -o $@ ${CFlAGS} ${CLIBS}
q8: 8-autocorrelation.c
	${CC} $^ -o $@ ${CFlAGS} ${CLIBS}
q9: 9-chi_square.c
	${CC} $^ -o $@ ${CFlAGS} # ${CLIBS}
q10: 10-gap.c
	${CC} $^ -o $@ ${CFlAGS} ${CLIBS}

clean:
	rm *~ q1 q2 q3 q4 q5 q6 q7 q8 q9 q10
